# -*- coding: utf-8 -*-
"""KoreaUniv Augmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQfZH9rOZq2kNuW5Eac6I4Ys3FI98ESk
"""

# Import necessary libraries
import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# Download CIFAR-10 dataset
transform = transforms.Compose([
    transforms.ToTensor(),  # Convert images to tensor
])

# Load CIFAR10 dataset (small dataset, suitable for quick demos)
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = DataLoader(trainset, batch_size=4, shuffle=True)

# Helper function to show images
def imshow(img):
    img = img / 2 + 0.5  # Unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.axis('off')
    plt.show()

# Display some sample images
dataiter = iter(trainloader)
images, labels = next(dataiter)  # Corrected line
imshow(torchvision.utils.make_grid(images))

class RGBShift:
    """Randomly shift RGB channels in an image."""
    def __init__(self, r_shift=0.1, g_shift=0.1, b_shift=0.1):
        self.r_shift = r_shift
        self.g_shift = g_shift
        self.b_shift = b_shift

    def __call__(self, img):
        # Apply random shift to each channel
        r_shift = (torch.rand(1) - 0.5) * 2 * self.r_shift
        g_shift = (torch.rand(1) - 0.5) * 2 * self.g_shift
        b_shift = (torch.rand(1) - 0.5) * 2 * self.b_shift
        img[0] = torch.clamp(img[0] + r_shift, 0, 1)
        img[1] = torch.clamp(img[1] + g_shift, 0, 1)
        img[2] = torch.clamp(img[2] + b_shift, 0, 1)
        return img

# Apply RGB shift and visualize
rgb_shift = RGBShift()
shifted_images = torch.stack([rgb_shift(img) for img in images])
imshow(torchvision.utils.make_grid(shifted_images))

# Define random rotation transform
rotate_transform = transforms.RandomRotation(30)  # Rotate by +/- 30 degrees

# Apply rotation and visualize
rotated_images = torch.stack([rotate_transform(img) for img in images])
imshow(torchvision.utils.make_grid(rotated_images))

class StyleTransfer:
    """Apply simple style transfer by adding random noise to image."""
    def __init__(self, noise_level=0.1):
        self.noise_level = noise_level

    def __call__(self, img):
        noise = torch.randn_like(img) * self.noise_level
        return torch.clamp(img + noise, 0, 1)

# Apply style transfer and visualize
style_transfer = StyleTransfer(noise_level=0.1)
styled_images = torch.stack([style_transfer(img) for img in images])
imshow(torchvision.utils.make_grid(styled_images))

import torch.nn as nn
import torch.optim as optim

# Define a simple CNN model
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Initialize the model, loss function, and optimizer
model = SimpleCNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

# Training function
def train_model(trainloader, epochs=2):
    for epoch in range(epochs):
        running_loss = 0.0
        for i, data in enumerate(trainloader, 0):
            inputs, labels = data
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"Epoch {epoch + 1}, Loss: {running_loss / len(trainloader)}")

# Train and evaluate for each augmentation
print("Training on Original Data:")
train_model(trainloader)

# RGB Shift Augmented Data
shifted_dataset = [(rgb_shift(img), label) for img, label in trainset]
shifted_loader = DataLoader(shifted_dataset, batch_size=4, shuffle=True)
print("\nTraining on RGB Shift Augmented Data:")
train_model(shifted_loader)

# Rotated Data
rotated_dataset = [(rotate_transform(img), label) for img, label in trainset]
rotated_loader = DataLoader(rotated_dataset, batch_size=4, shuffle=True)
print("\nTraining on Rotated Data:")
train_model(rotated_loader)

# Styled Data
styled_dataset = [(style_transfer(img), label) for img, label in trainset]
styled_loader = DataLoader(styled_dataset, batch_size=4, shuffle=True)
print("\nTraining on Styled Data:")
train_model(styled_loader)

