# -*- coding: utf-8 -*-
"""WeightPredictiontesting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FmwtNRJ3wUEN6ULMGpikhM6XWbY-H4n

#Installation
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as stats
import seaborn as sns
from imblearn.over_sampling import SMOTE
from scipy.stats import boxcox
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, PolynomialFeatures, QuantileTransformer
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor,RandomForestClassifier
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_predict
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline as imbPipeline

"""#Feature Engineering"""

df = pd.read_csv("question3-train.csv", encoding='ISO-8859-1', low_memory=False)

categorical_col=['Sex', 'Event', 'Equipment', 'AgeClass', 'BirthYearClass',
       'Division', 'Federation', 'MeetCountry', 'MeetTown', 'MeetName',
       'Sanctioned']
numerical_col=[ 'Age','BodyweightKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg',
               'Best3BenchKg', 'Place', 'Dots', 'Wilks', 'Glossbrenner','Goodlift']

# Categorical 컬럼에서 결측치 개수 확인
categorical_missing = df[categorical_col].isnull().sum()

# Numerical 컬럼에서 결측치 개수 확인
numerical_missing = df[numerical_col].isnull().sum()

# 결과 출력
print("Categorical 컬럼 결측치 개수:")
print(categorical_missing)
print("\nNumerical 컬럼 결측치 개수:")
print(numerical_missing)

print("\n범주형 변수의 분포:")
for col in categorical_col:
    print(f"\n컬럼명: {col}")
    print(df[col].value_counts())

"""#EDA (이상치는 아직 처리안함, 결측치만)

## Sex, Event 처리하기
"""

# L 열 이전의 값들을 한 칸씩 밀면서, Sex와 Event 값을 처리하는 함수
def shift_row_limited(row):
    if row['Sex'] in ['SBD', 'B', 'D','BD']:  # Sex에 잘못된 값이 들어간 경우
        original_event = row['Event']  # 기존의 Event 값을 저장
        row['Event'] = row['Sex']  # Sex 값을 Event로 이동
        row['Sex'] = 'Unknown'  # Sex는 Unknown으로 설정

        # L열 이전까지만 데이터를 한 칸씩 오른쪽으로 이동
        columns_to_shift = df.columns[2:]  # L 열 전까지 범위를 설정 (정확한 열 번호 확인 필요)

        # 기존 Event 값을 오른쪽으로 이동
        shifted_values = row[columns_to_shift].shift(1)  # 한 칸씩 오른쪽으로 이동
        shifted_values.iloc[0] = original_event  # 이동된 값의 첫 번째 위치에 기존 Event 값 넣기
        row.update(shifted_values)  # 업데이트
    return row

# 이상한 행들만 필터링하고, 적용
df.loc[df['Sex'].isin(['SBD', 'B', 'D','BD'])] = df.loc[df['Sex'].isin(['SBD', 'B', 'D','BD'])].apply(shift_row_limited, axis=1)

# Sex 컬럼에서 'Mx'를 'M'으로 대체
df['Sex'] = df['Sex'].replace('Mx', 'M')

# 결과 확인
print(df['Sex'].value_counts())  # Sex 값들이 제대로 변경되었는지 확인

"""## Age 처리하기"""

# Age 열의 데이터 타입 확인
print(df['Age'].dtype)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
print(df['Age'].dtype)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
# AgeClass에서 잘못된 값들을 적절한 값으로 대체
df['AgeClass'] = df['AgeClass'].replace({'05¿ù 12ÀÏ': '5-12', '80-999': '80-99'})
#df['AgeClass'] = df['AgeClass'].replace({'05Â¿Ã¹ 12ÃÃ': '5-12', '80-999': '80-99'})
# AgeClass의 범위에 따라 Age 결측치를 채우는 함수
def fill_age_based_on_class(row):
    if pd.isnull(row['Age']) and pd.notnull(row['AgeClass']):
        age_class = row['AgeClass']
        # AgeClass에 따라 평균값 또는 중앙값을 사용해 Age 결측치를 채움
        if age_class == '5-12':
            return 10  # 5~12세의 중간값
        elif age_class == '13-15':
            return 14
        elif age_class == '16-17':
            return 16.5
        elif age_class == '18-19':
            return 18.5
        elif age_class == '20-23':
            return 21.5
        elif age_class == '24-34':
            return 29
        elif age_class == '35-39':
            return 37
        elif age_class == '40-44':
            return 42
        elif age_class == '45-49':
            return 47
        elif age_class == '50-54':
            return 52
        elif age_class == '55-59':
            return 57
        elif age_class == '60-64':
            return 62
        elif age_class == '65-69':
            return 67
        elif age_class == '70-74':
            return 72
        elif age_class == '75-79':
            return 77
        elif age_class == '80-99':
            return 80
    return row['Age']  # Age가 이미 있는 경우에는 그대로 유지

# 결측치 채우기
df['Age'] = df.apply(fill_age_based_on_class, axis=1)

# Division별로 Age의 평균을 계산한 후 결측치를 대체하는 함수
def fill_age_with_group_mean(df):
    # Division별로 Age의 평균 계산
    division_age_means = df.groupby('Division')['Age'].mean()

    # Age가 결측치인 경우, Division별 평균으로 대체
    df['Age'] = df.apply(
        lambda row: division_age_means.get(row['Division'], None) if pd.isnull(row['Age']) else row['Age'],
        axis=1
    )

    # 여전히 결측치인 Age의 개수를 계산
    missing_age_count = df['Age'].isnull().sum()
    print(f"여전히 결측치인 Age 개수: {missing_age_count}")

    return df

# Age의 결측치를 Division별 평균으로 대체
df = fill_age_with_group_mean(df)

# 결과 확인
print(df['Age'].isnull().sum())

#missing values
print(df.isnull().sum())

"""##Bench 기록들 해결하기"""

# Bench1Kg, Bench2Kg, Bench3Kg을 숫자형으로 변환 (숫자가 아닌 값은 NaN으로 처리)
df.loc[:, 'Bench1Kg'] = pd.to_numeric(df['Bench1Kg'], errors='coerce')
df.loc[:, 'Bench2Kg'] = pd.to_numeric(df['Bench2Kg'], errors='coerce')
df.loc[:, 'Bench3Kg'] = pd.to_numeric(df['Bench3Kg'], errors='coerce')

# 음수값을 양수로 변경 (절대값 사용)
df.loc[:, 'Bench1Kg'] = df['Bench1Kg'].abs()
df.loc[:, 'Bench2Kg'] = df['Bench2Kg'].abs()
df.loc[:, 'Bench3Kg'] = df['Bench3Kg'].abs()

# Bench1Kg, Bench2Kg, Bench3Kg의 평균을 계산하여 새로운 'Average Bench' 열 생성
df.loc[:, 'Average Bench'] = df[['Bench1Kg', 'Bench2Kg', 'Bench3Kg']].mean(axis=1)

# 'Best3BenchKg'의 결측치를 'Average Bench' 값으로 대체
df.loc[:, 'Best3BenchKg'] = df['Best3BenchKg'].fillna(df['Average Bench'])

# 결과 확인
print(df[['Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Average Bench', 'Best3BenchKg']].head())

"""## TotalKg 결측치 해결"""

for col in numerical_col:
    df[col] = pd.to_numeric(df[col], errors='coerce')
target_col=['TotalKg']
df = df.dropna(subset=['TotalKg','BodyweightKg','Age','Dots','Best3BenchKg'])
#df = df[~((df['Sex'] == 'Unknown'))]

df['Average_Score'] = df[['Wilks', 'Dots', 'Glossbrenner']].mean(axis=1)

#기존 전처리로 고쳐보자
일단 이 코드를 외워줘. df = pd.read_csv("question3-train.csv", encoding='ISO-8859-1', low_memory=False)
# L 열 이전의 값들을 한 칸씩 밀면서, Sex와 Event 값을 처리하는 함수
def shift_row_limited(row):
    if row['Sex'] in ['SBD', 'B', 'D','BD']:  # Sex에 잘못된 값이 들어간 경우
        original_event = row['Event']  # 기존의 Event 값을 저장
        row['Event'] = row['Sex']  # Sex 값을 Event로 이동
        row['Sex'] = 'Unknown'  # Sex는 Unknown으로 설정

        # L열 이전까지만 데이터를 한 칸씩 오른쪽으로 이동
        columns_to_shift = df.columns[2:]  # L 열 전까지 범위를 설정 (정확한 열 번호 확인 필요)

        # 기존 Event 값을 오른쪽으로 이동
        shifted_values = row[columns_to_shift].shift(1)  # 한 칸씩 오른쪽으로 이동
        shifted_values.iloc[0] = original_event  # 이동된 값의 첫 번째 위치에 기존 Event 값 넣기
        row.update(shifted_values)  # 업데이트
    return row

# 이상한 행들만 필터링하고, 적용
df.loc[df['Sex'].isin(['SBD', 'B', 'D','BD'])] = df.loc[df['Sex'].isin(['SBD', 'B', 'D','BD'])].apply(shift_row_limited, axis=1)

# Sex 컬럼에서 'Mx'를 'M'으로 대체
df['Sex'] = df['Sex'].replace('Mx', 'M')

# 결과 확인
print(df['Sex'].value_counts())  # Sex 값들이 제대로 변경되었는지 확인

# Age 열의 데이터 타입 확인
print(df['Age'].dtype)
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
print(df['Age'].dtype)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
# AgeClass에서 잘못된 값들을 적절한 값으로 대체
df['AgeClass'] = df['AgeClass'].replace({'05¿ù 12ÀÏ': '5-12', '80-999': '80-99'})
#df['AgeClass'] = df['AgeClass'].replace({'05Â¿Ã¹ 12ÃÃ': '5-12', '80-999': '80-99'})
# AgeClass의 범위에 따라 Age 결측치를 채우는 함수
def fill_age_based_on_class(row):
    if pd.isnull(row['Age']) and pd.notnull(row['AgeClass']):
        age_class = row['AgeClass']
        # AgeClass에 따라 평균값 또는 중앙값을 사용해 Age 결측치를 채움
        if age_class == '5-12':
            return 10  # 5~12세의 중간값
        elif age_class == '13-15':
            return 14
        elif age_class == '16-17':
            return 16.5
        elif age_class == '18-19':
            return 18.5
        elif age_class == '20-23':
            return 21.5
        elif age_class == '24-34':
            return 29
        elif age_class == '35-39':
            return 37
        elif age_class == '40-44':
            return 42
        elif age_class == '45-49':
            return 47
        elif age_class == '50-54':
            return 52
        elif age_class == '55-59':
            return 57
        elif age_class == '60-64':
            return 62
        elif age_class == '65-69':
            return 67
        elif age_class == '70-74':
            return 72
        elif age_class == '75-79':
            return 77
        elif age_class == '80-99':
            return 80
    return row['Age']  # Age가 이미 있는 경우에는 그대로 유지

# 결측치 채우기
df['Age'] = df.apply(fill_age_based_on_class, axis=1)

# Division별로 Age의 평균을 계산한 후 결측치를 대체하는 함수
def fill_age_with_group_mean(df):
    # Division별로 Age의 평균 계산
    division_age_means = df.groupby('Division')['Age'].mean()

    # Age가 결측치인 경우, Division별 평균으로 대체
    df['Age'] = df.apply(
        lambda row: division_age_means.get(row['Division'], None) if pd.isnull(row['Age']) else row['Age'],
        axis=1
    )

    # 여전히 결측치인 Age의 개수를 계산
    missing_age_count = df['Age'].isnull().sum()
    print(f"여전히 결측치인 Age 개수: {missing_age_count}")

    return df

# Age의 결측치를 Division별 평균으로 대체
df = fill_age_with_group_mean(df)

# 결과 확인
print(df['Age'].isnull().sum())

# 결측치가 있는 행 삭제
df = df.dropna(subset=['Age'])

#추가 보완코딩가능

# Bench1Kg, Bench2Kg, Bench3Kg을 숫자형으로 변환 (숫자가 아닌 값은 NaN으로 처리)
df.loc[:, 'Bench1Kg'] = pd.to_numeric(df['Bench1Kg'], errors='coerce')
df.loc[:, 'Bench2Kg'] = pd.to_numeric(df['Bench2Kg'], errors='coerce')
df.loc[:, 'Bench3Kg'] = pd.to_numeric(df['Bench3Kg'], errors='coerce')

# 음수값을 양수로 변경 (절대값 사용)
df.loc[:, 'Bench1Kg'] = df['Bench1Kg'].abs()
df.loc[:, 'Bench2Kg'] = df['Bench2Kg'].abs()
df.loc[:, 'Bench3Kg'] = df['Bench3Kg'].abs()

# Bench1Kg, Bench2Kg, Bench3Kg의 평균을 계산하여 새로운 'Average Bench' 열 생성
df.loc[:, 'Average Bench'] = df[['Bench1Kg', 'Bench2Kg', 'Bench3Kg']].mean(axis=1)

# 'Best3BenchKg'의 결측치를 'Average Bench' 값으로 대체
df.loc[:, 'Best3BenchKg'] = df['Best3BenchKg'].fillna(df['Average Bench'])

# 결과 확인
print(df[['Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Average Bench', 'Best3BenchKg']].head())

df = df.dropna(subset=['TotalKg'])
# BodyweightKg와 Dots에서 결측치가 있는 행 제거
df = df.dropna(subset=['BodyweightKg', 'Dots'])
df = df.dropna(subset=['Division','MeetCountry'])

#극단적인 경우
# Sex가 'Unknown'이거나 Best3BenchKg가 결측치인 데이터를 제거
df = df[~((df['Sex'] == 'Unknown') | (df['Best3BenchKg'].isnull()))]

df['Average_Score'] = df[['Wilks', 'Dots', 'Glossbrenner']].mean(axis=1)
target_col=['TotalKg']
categorical_col=['Sex', 'Event'] #Federation, Country, 'Equipment'
numerical_col=[ 'Age', 'BodyweightKg','Best3BenchKg', 'Average_Score']

X_train=df[categorical_col+numerical_col]
y_train=df[target_col]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_col),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_col)
    ],
    remainder='passthrough'
)

model_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('regressor', RandomForestRegressor(random_state=42))
    ]
)

model_pipeline.fit(X_train, y_train)

# 'Sex'가 'Unknown'인 행을 BodyweightKg 값으로 구분하여 성별 평균값으로 대체
# 성별별 평균 BodyweightKg 계산
male_avg_weight = df[df['Sex'] == 'M']['BodyweightKg'].mean()
female_avg_weight = df[df['Sex'] == 'F']['BodyweightKg'].mean()

# 'Sex'가 'Unknown'이고 BodyweightKg가 남성 평균보다 크면 'M', 그렇지 않으면 'F'로 예측
df.loc[(df['Sex'] == 'Unknown') & (df['BodyweightKg'] >= male_avg_weight), 'Sex'] = 'M'
df.loc[(df['Sex'] == 'Unknown') & (df['BodyweightKg'] < male_avg_weight), 'Sex'] = 'F'

# Division 기준으로 결측값 대체
df['Age'].fillna(df.groupby('Division')['Age'].transform('mean'), inplace=True)
df['BodyweightKg'].fillna(df.groupby('Division')['BodyweightKg'].transform('mean'), inplace=True)
df['Average_Score'].fillna(df.groupby('Division')['Average_Score'].transform('mean'), inplace=True)
df['Best3BenchKg'].fillna(df.groupby('Division')['Best3BenchKg'].transform('mean'), inplace=True)

# 여전히 남아 있는 결측값이 있다면, Sex 기준으로 대체
df['Age'].fillna(df.groupby('Sex')['Age'].transform('mean'), inplace=True)
df['BodyweightKg'].fillna(df.groupby('Sex')['BodyweightKg'].transform('mean'), inplace=True)
df['Average_Score'].fillna(df.groupby('Sex')['Average_Score'].transform('mean'), inplace=True)
df['Best3BenchKg'].fillna(df.groupby('Sex')['Best3BenchKg'].transform('mean'), inplace=True)

"""## Sex, BestBench3 해결하기

#Modeling
"""

df.columns

# 필수 열 정의
target_col = ['TotalKg']  # 타겟 열이 TotalKg라고 가정
categorical_col = ['Sex', 'Event']
numerical_col = ['Age', 'BodyweightKg', 'Average_Score']
categorical_col2 = ['Sex', 'Event']
numerical_col2 = ['Age', 'BodyweightKg', 'Best3BenchKg', 'Average_Score']

# EVENT가 'S', 'D', 'SD'인 데이터셋
df_event_sdsd = df[df['Event'].isin(['S', 'D', 'SD'])]
X_train_sdsd = df_event_sdsd[categorical_col + numerical_col]
y_train_sdsd = df_event_sdsd[target_col]

# 나머지 EVENT 데이터셋
df_other_events = df[~df['Event'].isin(['S', 'D', 'SD'])]
X_train_other = df_other_events[categorical_col2 + numerical_col2]
y_train_other = df_other_events[target_col]

preprocessor1 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_col),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_col)
    ],
    remainder='passthrough'
)

preprocessor2 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_col2),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_col2)
    ],
    remainder='passthrough'
)

model_pipeline1 = Pipeline(
    steps=[
        ('preprocessor', preprocessor1),
        ('regressor', RandomForestRegressor(random_state=42))
    ]
)

model_pipeline2 = Pipeline(
    steps=[
        ('preprocessor', preprocessor2),
        ('regressor', RandomForestRegressor(random_state=42))
    ]
)

model_pipeline1.fit(X_train_sdsd, y_train_sdsd)
model_pipeline2.fit(X_train_other, y_train_other)

# 필수 열 정의
target_col = ['TotalKg']  # 타겟 열이 TotalKg라고 가정
categorical_col = ['Sex', 'Event']
numerical_col = ['Age', 'BodyweightKg', 'Average_Score']
categorical_col2 = ['Sex', 'Event']
numerical_col2 = ['Age', 'BodyweightKg', 'Best3BenchKg', 'Average_Score']

# EVENT가 'S', 'D', 'SD'인 데이터셋
df_event_sdsd = df[df['Event'].isin(['S', 'D', 'SD'])]
X_train_sdsd = df_event_sdsd[categorical_col + numerical_col]
y_train_sdsd = df_event_sdsd[target_col]

# 나머지 EVENT 데이터셋
df_other_events = df[~df['Event'].isin(['S', 'D', 'SD'])]
X_train_other = df_other_events[categorical_col2 + numerical_col2]
y_train_other = df_other_events[target_col]

X_train_sdsd, X_val_sdsd, y_train_sdsd, y_val_sdsd = train_test_split(X_train_sdsd, y_train_sdsd, test_size=0.2, random_state=42)
X_train_other, X_val_other, y_train_other, y_val_other = train_test_split(X_train_other, y_train_other, test_size=0.2, random_state=42)

preprocessor1 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_col),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_col)
    ],
    remainder='passthrough'
)

preprocessor2 = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_col2),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_col2)
    ],
    remainder='passthrough'
)

model_pipeline1 = Pipeline(
    steps=[
        ('preprocessor', preprocessor1),
        ('regressor', RandomForestRegressor(random_state=42))
    ]
)

model_pipeline2 = Pipeline(
    steps=[
        ('preprocessor', preprocessor2),
        ('regressor', RandomForestRegressor(random_state=42))
    ]
)

model_pipeline1.fit(X_train_sdsd, y_train_sdsd)
model_pipeline2.fit(X_train_other, y_train_other)
# 검증 데이터에 대한 예측
y_pred_sdsd = model_pipeline1.predict(X_val_sdsd)
#y_pred_other = model_pipeline2.predict(X_val_other)

# MSE 계산
mse_sdsd = mean_squared_error(y_val_sdsd, y_pred_sdsd)
mse_other = mean_squared_error(y_val_other, y_pred_other)

print(f"MSE for S, D, SD events: {mse_sdsd}")
print(f"MSE for other events: {mse_other}")

# 학습 및 검증 데이터에 문자열이 포함된 열이 있는지 확인
print("X_train_sdsd types:\n", X_train_sdsd.dtypes)
print("X_train_other types:\n", X_train_other.dtypes)
print("X_val_sdsd types:\n", X_val_sdsd.dtypes)
print("X_val_other types:\n", X_val_other.dtypes)

#예측 수행
y_pred_sdsd = model_pipeline1.predict(X_train_sdsd)
y_pred_other = model_pipeline2.predict(X_train_other)

# 예측값을 원본 데이터프레임에 추가
df_event_sdsd['y_pred'] = y_pred_sdsd  # S, D, SD에 대한 예측값
df_other_events['y_pred'] = y_pred_other  # 나머지 EVENT에 대한 예측값

# 결과 병합을 위해 index를 유지하면서 필요한 열만 선택
df_event_sdsd_result = df_event_sdsd[['index', 'TotalKg', 'y_pred']]
df_other_events_result = df_other_events[['index', 'TotalKg', 'y_pred']]

# 결과 병합 (인덱스를 유지한 채로)
result_df = pd.concat([df_event_sdsd_result, df_other_events_result]).sort_index()

# 최종 결과 출력 (원래 순서대로 정렬된 상태)
print(result_df[['TotalKg', 'y_pred']])

# MSE 계산 (S, D, SD 이벤트에 대한 MSE)
mse_sdsd = mean_squared_error(df_event_sdsd['TotalKg'], df_event_sdsd['y_pred'])

# MSE 계산 (나머지 이벤트에 대한 MSE)
mse_other = mean_squared_error(df_other_events['TotalKg'], df_other_events['y_pred'])

# 결과 출력
print("MSE (S, D, SD 이벤트):", mse_sdsd)
print("MSE (나머지 이벤트):", mse_other)

print("\n범주형 변수의 분포:")
for col in categorical_col:
    print(f"\n컬럼명: {col}")
    print(df[col].value_counts())

"""## 테스트 파일 받기"""

# 엑셀 파일 읽기 및 열 이름 수정
df2 = pd.read_csv("question3-test - features.csv", encoding='ISO-8859-1', low_memory=False)
# 'ï»¿Sex'를 'Sex'로 열 이름 변경
df2.rename(columns={'ï»¿Sex': 'Sex'}, inplace=True)
df2['Average_Score'] = df[['Wilks', 'Dots', 'Glossbrenner']].mean(axis=1)

df2.columns

categorical_col=['Sex', 'Event', 'Equipment', 'AgeClass', 'BirthYearClass',
       'Division', 'Federation', 'MeetCountry', 'MeetTown', 'MeetName',
       'Sanctioned']
numerical_col=[ 'Age','BodyweightKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg',
               'Best3BenchKg', 'Place', 'Dots', 'Wilks', 'Glossbrenner','Goodlift']

# Categorical 컬럼에서 결측치 개수 확인
categorical_missing = df2[categorical_col].isnull().sum()

# Numerical 컬럼에서 결측치 개수 확인
numerical_missing = df2[numerical_col].isnull().sum()

# 결과 출력
print("Categorical 컬럼 결측치 개수:")
print(categorical_missing)
print("\nNumerical 컬럼 결측치 개수:")
print(numerical_missing)

print("\n범주형 변수의 분포:")
for col in categorical_col:
    print(f"\n컬럼명: {col}")
    print(df2[col].value_counts())

# Bench1Kg, Bench2Kg, Bench3Kg을 숫자형으로 변환 (숫자가 아닌 값은 NaN으로 처리)
df2.loc[:, 'Bench1Kg'] = pd.to_numeric(df2['Bench1Kg'], errors='coerce')
df2.loc[:, 'Bench2Kg'] = pd.to_numeric(df2['Bench2Kg'], errors='coerce')
df2.loc[:, 'Bench3Kg'] = pd.to_numeric(df2['Bench3Kg'], errors='coerce')

# 음수값을 양수로 변경 (절대값 사용)
df2.loc[:, 'Bench1Kg'] = df2['Bench1Kg'].abs()
df2.loc[:, 'Bench2Kg'] = df2['Bench2Kg'].abs()
df2.loc[:, 'Bench3Kg'] = df2['Bench3Kg'].abs()

# Bench1Kg, Bench2Kg, Bench3Kg의 평균을 계산하여 새로운 'Average Bench' 열 생성
df2.loc[:, 'Average Bench'] = df2[['Bench1Kg', 'Bench2Kg', 'Bench3Kg']].mean(axis=1)

# 'Best3BenchKg'의 결측치를 'Average Bench' 값으로 대체
df2.loc[:, 'Best3BenchKg'] = df2['Best3BenchKg'].fillna(df2['Average Bench'])

df2['Average_Score'] = df2[['Wilks', 'Dots', 'Glossbrenner']].mean(axis=1)
# 결과 확인
print(df2[['Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Average Bench', 'Best3BenchKg']].head())

# SEX와 EVENT 잘못된 값 처리
df2.loc[df2['Sex'].isin(['SBD', 'B', 'D', 'BD'])] = df2.loc[df2['Sex'].isin(['SBD', 'B', 'D', 'BD'])].apply(shift_row_limited, axis=1)

# Sex 컬럼에서 'Mx'를 'M'으로 변경 (apply 사용)
df2['Sex'] = df2['Sex'].apply(lambda x: 'M' if x == 'Mx' else x)

"""## 테스트 Age 처리"""

#missing values
print(df2.isnull().sum())

# Age 열의 데이터 타입 확인
print(df2['Age'].dtype)
df2['Age'] = pd.to_numeric(df2['Age'], errors='coerce')
print(df2['Age'].dtype)

print("\n범주형 변수의 분포:")
print(df2['AgeClass'].value_counts())

# 1. 먼저 df2에서 fill_age_based_on_class 적용
df2['AgeClass'] = df2['AgeClass'].replace({'05ì 12ì¼': '5-12', '80-999': '80-99'})
df2['Age'] = df2.apply(fill_age_based_on_class, axis=1)

# Division별로 Age의 평균을 계산한 후 결측치를 대체하는 함수
def fill_age_with_group_mean(df,df2):
    # Division별로 Age의 평균 계산
    division_age_means = df.groupby('Division')['Age'].mean()

    # Age가 결측치인 경우, Division별 평균으로 대체
    df2['Age'] = df2.apply(
        lambda row: division_age_means.get(row['Division'], None) if pd.isnull(row['Age']) else row['Age'],
        axis=1
    )

    # 여전히 결측치인 Age의 개수를 계산
    missing_age_count = df2['Age'].isnull().sum()
    print(f"여전히 결측치인 Age 개수: {missing_age_count}")

    return df2

# Age의 결측치를 Division별 평균으로 대체
df2 = fill_age_with_group_mean(df,df2)

# df2에서 여전히 결측치가 있는지 확인
print(f"df2에서 여전히 결측치인 Age 개수: {df2['Age'].isnull().sum()}")

for col in numerical_col:
    df2[col] = pd.to_numeric(df2[col], errors='coerce')

# 'Sex'가 'Unknown'인 행을 BodyweightKg 값으로 구분하여 성별 평균값으로 대체
# 성별별 평균 BodyweightKg 계산
male_avg_weight = df2[df2['Sex'] == 'M']['BodyweightKg'].mean()
female_avg_weight = df2[df2['Sex'] == 'F']['BodyweightKg'].mean()

# 'Sex'가 'Unknown'이고 BodyweightKg가 남성 평균보다 크면 'M', 그렇지 않으면 'F'로 예측
df2.loc[(df2['Sex'] == 'Unknown') & (df2['BodyweightKg'] >= male_avg_weight), 'Sex'] = 'M'
df2.loc[(df2['Sex'] == 'Unknown') & (df2['BodyweightKg'] < male_avg_weight), 'Sex'] = 'F'

# Division 기준으로 결측값 대체
df2['Age'].fillna(df2.groupby('Division')['Age'].transform('mean'), inplace=True)
df2['BodyweightKg'].fillna(df2.groupby('Division')['BodyweightKg'].transform('mean'), inplace=True)
df2['Average_Score'].fillna(df2.groupby('Division')['Average_Score'].transform('mean'), inplace=True)
df2['Best3BenchKg'].fillna(df2.groupby('Division')['Best3BenchKg'].transform('mean'), inplace=True)

# 여전히 남아 있는 결측값이 있다면, Sex 기준으로 대체
df2['Age'].fillna(df2.groupby('Sex')['Age'].transform('mean'), inplace=True)
df2['BodyweightKg'].fillna(df2.groupby('Sex')['BodyweightKg'].transform('mean'), inplace=True)
df2['Average_Score'].fillna(df2.groupby('Sex')['Average_Score'].transform('mean'), inplace=True)
df2['Best3BenchKg'].fillna(df2.groupby('Sex')['Best3BenchKg'].transform('mean'), inplace=True)

categorical_col = ['Sex', 'Event']
numerical_col = ['Age', 'BodyweightKg', 'Average_Score']
categorical_col2 = ['Sex', 'Event']
numerical_col2 = ['Age', 'BodyweightKg', 'Best3BenchKg', 'Average_Score']

# EVENT가 'S', 'D', 'SD'인 데이터셋
df2_event_sdsd = df2[df2['Event'].isin(['S', 'D', 'SD'])]
X_test_sdsd = df2_event_sdsd[categorical_col + numerical_col]

# 나머지 EVENT 데이터셋
df2_other_events = df2[~df2['Event'].isin(['S', 'D', 'SD'])]
X_test_other = df2_other_events[categorical_col2 + numerical_col2]

# 모델 예측 수행
y_pred_sdsd = model_pipeline1.predict(X_test_sdsd)
y_pred_other = model_pipeline2.predict(X_test_other)

# 예측 결과를 'pred' 열에 추가
df2.loc[df2['Event'].isin(['S', 'D', 'SD']), 'pred'] = y_pred_sdsd
df2.loc[~df2['Event'].isin(['S', 'D', 'SD']), 'pred'] = y_pred_other

# 예측 결과 확인
print(df2[['Event', 'pred']].head(40))

output_filename = "predicted_results.csv"
df2.to_csv(output_filename, index=False, encoding='utf-8-sig')  # UTF-8 with BOM for compatibility

print(f"예측 결과가 '{output_filename}' 파일에 저장되었습니다.")

print(df2.columns)

#missing values
print(df2.isnull().sum())